const kahani = [
    "Hi, I am a story",
    "Sorry, if I am not that interesting. But Let's see how it goes",
    "Its been more then a year, and I still miss you",
    "I still remember the day we met",
    "Shopper's Stop ki bench",
    "Metro par drop karna",
    "Our cute Auto rides 🥰",
    "Tumhe surprise karna, tumhe choclates dena, tumhare liye keychains lana 🙈",
    "Please say NO to Tushar ⚔️",
    "Sorry, I left you 🚶🏽            🧍🏻‍♀️",
    "Sorry, maine tumhe fir manaya nahi 🧎🏽‍♂️",
    "Sorry, I ignored you 🧎🏽‍♂️",
    "But I beleive, abhi bhi der nahi huyi hai",
    "Still, I saw you in my dreams 🥰",
    "Aditya inside me is not accepting to loose you 😕",
    "When I saw Tushar's comment on your every photo, I thought i've lost you",
    "I felt the same, that i felt on the day your sagai got fixed",
    "kal tak mai paresan tha jab tak baat nahi huyi thi 😖",
    "fir baat karke kuch magic ho gya, the same magic jo tumhare saath reh kar humesa hota tha 🤩",
    "dekho na, fir se tumhe surprise karne ke ideas aa gye 💐💝",
    "I felt the same happiness, the same joy, the same love jo saath mai hota tha 😇",
    "Lets not punish ourself, lets not punish our love , and accept the magic we feel when we were together 🙇🏻‍♀️🙇🏻",
    "I will support you in everything, Mummy Papa ko saath mai milkar samjha lenge yaaar",
    "Itna samjha hai ghar walo ne, aaj bhi samjh lenge",
    "Just dont say YES to Tushar",
    "Say YES to me",
    "Say YES to me, and NO to Tushar",
    "Say YES to our love",
    "YES to our future",
    "YES to our marriage",
    "YES to our life",
    "YES to our happiness",
    "YES to our love story",
    "YES to our love story forever",
    "our love story forever and ever and ever",
  ];

  export default kahani